words = ["apple", "banana", "cherry", "dog", "elephant", "frog", "grape", "horse", "iguana", "jaguar",
         "kangaroo", "lemon", "monkey", "notebook", "orange", "parrot", "queen", "rabbit", "strawberry", "tiger",
         "umbrella", "violin", "watermelon", "xylophone", "yogurt", "zebra", "avocado", "butterfly", "carrot", "diamond",
         "eagle", "fish", "guitar", "hat", "ice cream", "jellyfish", "kiwi", "lion", "mango", "necklace", "octopus",
         "panda", "quill", "raccoon", "sunflower", "turtle", "ukulele", "volcano", "whale", "xylophone", "yacht",
         "zucchini", "antelope", "bear", "cupcake", "donut", "elephant", "flamingo", "giraffe", "helicopter", "ice",
         "jelly", "kite", "lollipop", "mountain", "nest", "octagon", "pineapple", "queen bee", "rainbow", "seahorse",
         "turtle", "unicorn", "violin", "water", "x-ray", "yacht", "zipper", "ant", "boat", "cat", "dolphin",
         "egg", "fox", "guitar", "honey", "ice cream", "jellyfish", "koala", "lemonade", "mushroom", "nectar", "owl",
         "penguin", "rose", "strawberry", "tiger", "unicorn", "violin", "watermelon"]